# SPDX-FileCopyrightText: 2016-2024 Hnscloud GmbH and Hnscloud contributors
# SPDX-License-Identifier: MIT
codecov:
  branch: master
  ci:
    - drone.hns.vn

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default

github_checks:
    annotations: false
